# Directory of visualizations

```{r echo = FALSE, message = FALSE}
library(dplyr)
library(ggforce)
library(ggjoy)
```

```{r fig.width = 8, fig.asp = 1/4, message = FALSE, warning=FALSE}
theme_plot_icon <- function(bg_color = "#F5F8EA", line_color = "#243400") {
  line_size <- .8
  font_size <- 10
  theme_dviz_half_open() %+replace% theme(
    axis.text.x       = element_blank(),
    axis.text.y       = element_blank(),
    axis.title.x      = element_blank(),
    axis.title.y      = element_blank(),
    axis.line.x       = element_line(size = line_size, color = line_color),
    axis.line.y       = element_line(size = line_size, color = line_color),
    axis.ticks        = element_line(size = line_size, color = line_color),
    axis.ticks.length = grid::unit(4, "pt"),
    legend.position   = "none",
    plot.margin       = margin(2, font_size, font_size, font_size),
    plot.title        = element_text(hjust = 0.5, face = "bold", color = line_color,
                                     size = font_size,
                                     margin = margin(0, 0, 2, 0)),
    plot.background   = element_rect(fill = bg_color)
  )
}

# earth-brown
# HCL Wizard settings: 71, 80, 10, 18, 97, 1.5, 2
palette1 = c("#402B00", "#7F6B00", "#B6A87C", "#E2DAC4", "#FBF6EA")

# brown-green
# HCL Wizard settings: 86, 80, 10, 18, 97, 1.5, 2
palette2 = c("#313100", "#707000", "#ABAB7B", "#DCDCC3", "#F7F7EA")

# green-brown
# HCL Wizard settings: -265, 80, 10, 18, 97, 1.5, 2
palette3 = c("#243400", "#667300", "#A4AD7C", "#D8DDC4", "#F5F8EA")

# burgundy-red
# HCL Wizard settings: 17, 80, 10, 18, 97, 1.5, 2
palette4 = c("#670000", "#A1574F", "#CF9C98", "#F1D4D1", "#FFF3F2")

# brown-red
# HCL Wizard settings: 41, 80, 10, 18, 97, 1.5, 2
palette5 = c("#581900", "#96602B", "#C7A188", "#ECD6C9", "#FFF4ED")

# ocean-blue
# HCL Wizard settings: 241, 80, 10, 18, 97, 1.5, 2
palette6 = c("#003F9C", "#2372A3", "#8DACCC", "#CDDCEE", "#EFF7FF")

# steel-blue
# HCL Wizard settings: 257, 80, 10, 18, 97, 1.5, 2
palette7 = c("#0021B1", "#546AA8", "#9DA7CF", "#D4DAF0", "#F3F6FF")


palette <- palette1

n <- 15
x <- rnorm(15)
y <- .4*x + .6*rnorm(15)
df <- data.frame(x, y)
p1 <- ggplot(df, aes(x, y)) + 
  geom_point(color = palette[3], size = 2.4) + 
  scale_x_continuous(expand = c(.2, 0)) +
  scale_y_continuous(expand = c(.2, 0)) +
  labs(title = "Scatterplot") +
  theme_plot_icon(palette1[length(palette)], palette[1])

df <- data.frame(x = c(rnorm(1000, 1., 1.6), rnorm(350, 4, .4)))
p2 <- ggplot(df, aes(x)) +
  geom_density(fill = palette[4], color = palette[2], bw = .35) +
  scale_x_continuous(limits = c(-4.8, 6.8), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, .29), expand = c(0, 0)) +
  labs(title = "Density plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

p3 <- ggplot(df, aes(x)) +
  geom_histogram(fill = palette[4], color = palette[2], bins = 18) +
  scale_x_continuous(limits = c(-4.8, 6.8), expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, 290), 
                     expand = c(0, 0)) +
  labs(title = "Histogram") +
  theme_plot_icon(palette[length(palette)], palette[1])


plot_grid(p1, p2, p3, ncol = 4, scale = .9)
```

```{r fig.width = 8, fig.asp = 1/4, message = FALSE}
palette <- palette2

df <- data.frame(y = c(.3, .39, .48, .6, .25, .13, .22, .24, .45, .48, .3, .16),
                 x = factor(rep(1:4, 3)),
                 type = rep(c("A", "B", "C"), each = 4))
p1 <- ggplot(filter(df, x!=4), aes(x, y,
                                   fill=factor(type, levels = c("A", "C", "B")))) + 
  geom_col(position="dodge", color = palette[1],
           width = .7) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, .58)) +
  scale_fill_manual(values = palette[2:4]) +
  labs(title = "Bar plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

p2 <- ggplot(df, aes(x, y, fill=type)) + 
  geom_col(position="stack", color = palette[1]) +
  scale_y_continuous(expand = c(0, 0)) +
  scale_fill_manual(values = palette[2:4]) +
  labs(title = "Stacked bar plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

plot_grid(p1, p2, ncol = 4, scale = .9)
```

```{r fig.width = 8, fig.asp = 1/2, message = FALSE}
palette <- palette6

n <- 70
df <- data.frame(y = c(rnorm(n, 1, .8), rnorm(n, 2, .7), rnorm(n, 0, .5)),
                 type = rep(c("A", "B", "C"), each = n),
                 number = rep(c(2, 1, 3), each = n))
p1 <- ggplot(df, aes(x = type, y = y)) + geom_boxplot(color = palette[1], fill = palette[4]) +
  labs(title = "Boxplot") +
  theme_plot_icon(palette[length(palette)], palette[1])


p2 <- ggplot(df, aes(x = type, y = y)) + geom_violin(color = palette[1], fill = palette[4]) +
  labs(title = "Violin plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

p3 <- ggplot(df, aes(x = type, y = y)) + geom_jitter(color = palette[1], width = 0.3, size = .8) +
  labs(title = "Jittered points") +
  theme_plot_icon(palette[length(palette)], palette[1])

p4 <- ggplot(df, aes(x = type, y = y)) + geom_sina(color = palette[1], size = 0.8) +
  labs(title = "Sina plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

p5 <- ggplot(df, aes(x = y, fill = factor(type, levels = c("C", "A", "B")))) + 
  geom_density(alpha = 0.7, color = palette[1]) +
  scale_fill_manual(values = palette[2:4]) +
  labs(title = "Overlapping densities plot") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(limits = c(0, .95), expand = c(0, 0)) +
  theme_plot_icon(palette[length(palette)], palette[1])

p6 <- ggplot(df, aes(x = y, y = number, group = number)) + 
  geom_joy(alpha = 0.7, fill = palette[3], scale = 2.0) +
  labs(title = "Joyplot") +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(limits = c(1, 6.5), expand = c(0, 0)) +
  theme_plot_icon(palette[length(palette)], palette[1])

p7 <- ggplot(df, aes(x = y, fill = factor(type, levels = c("C", "A", "B")))) + 
  geom_density(alpha = 0.7, color = palette[1], position = "fill") +
  scale_fill_manual(values = palette[2:4]) +
  labs(title = "Stacked densities plot") +
  theme_plot_icon(palette[length(palette)], palette[1])

plot_grid(p1, p2, p3, p4, 
          p5, p6, p7, ncol = 4, scale = .9)
```
