```{r echo = FALSE, message = FALSE}
# run setup script
source("_common.R")
```

# Figure titles and captions {#figure-titles-captions}

```{r fig.width = 7, fig.asp = 0.75}

trendline <- factor("y ~ log(x)", levels = c("Middle East and North Africa",
                          "Sub Saharan Africa",
                          "Americas",
                          "Asia Pacific",
                          "Europe and Central Asia",
                          "y ~ log(x)"))


corruption %>% filter(year == 2015) %>% na.omit() %>%
  mutate(region = factor(region,
                         levels = c("Middle East and North Africa",
                                    "Sub Saharan Africa",
                                    "Americas",
                                    "Asia Pacific",
                                    "Europe and Central Asia",
                                    "y ~ log(x)"))) %>%
  ggplot(aes(cpi, hdi)) + 
    geom_smooth(aes(color = trendline, fill = trendline, shape = trendline),
                method = 'lm', formula = y~log(x), se = FALSE) +
    geom_point(aes(color = region, shape = region, fill = region),
               size = 2.5, alpha = 0.7) + 
    scale_fill_OkabeIto(name = NULL, order = c(1:5, 8)) +
    scale_color_OkabeIto(name = NULL, darken = 0.3, order = c(1:5, 8)) +
    scale_shape_manual(values = c(21:25, NA), name = NULL) +
    scale_y_continuous(limits = c(0.3, 1), breaks = c(0.2, 0.4, 0.6, 0.8, 1.0),
                       expand = c(0, 0),
                       name = "Human Development Index\n(1.0 = most developed)") +
    scale_x_continuous(limits = c(10, 95),
                       breaks = c(20, 40, 60, 80, 100),
                       expand = c(0, 0),
                       name = "Corruption Perceptions Index\n(100 = least corrupt)") +
    guides(colour = guide_legend(ncol = 3,
             override.aes = list(linetype = c(rep("blank", 5), "solid")))) +
    theme_minimal_hgrid() +
    theme(legend.position = "bottom",
          legend.justification = "right")
```
