---
title: "Fundamentals of Data Visualization"
author: "Claus O. Wilke"
description: "A guide to making visualizations that accurately reflect the data, tell a story, and look professional."
github-repo: clauswilke/dataviz
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    includes:
      in_header: html_includes/google_analytics.html
bibliography: "bibliography.bib"
biblio-style: "apalike"
link-citations: true
---

# Welcome {-}

This is an online preview of the book "Fundamentals of Data Visualization" to be published with O’Reilly Media, Inc. Completed chapters will be posted here as they become available.

The book is meant as a guide to making visualizations that accurately reflect the data, tell a story, and look professional. It has grown out of my experience of working with students and postdocs in my laboratory on thousands of data visualizations. Over the years, I have noticed that the same issues arise over and over. I have attempted to collect my accumulated knowledge from these interactions in the form of this book.

The entire book is written in R Markdown, using RStudio as my text editor and the **bookdown** package to turn a collection of markdown documents into a coherent whole. The book's source code is hosted on GitHub, at https://github.com/clauswilke/dataviz. If you notice typos or other issues, feel free to open an issue on GitHub or send me a pull request. If you do the latter, in your commit message, please add the sentence "I assign the copyright of this contribution to Claus O. Wilke," so that I can maintain the option of publishing this book in other forms.

This work is licensed under the [Attribution-NonCommercial-NoDerivatives 4.0 International](https://creativecommons.org/licenses/by-nc-nd/4.0/legalcode) License. 
