# Notes {-}

  
## Articles and blog posts with useful ideas {-}

- https://medium.com/@clmentviguier/how-to-turn-a-twitter-comment-into-a-data-visualisation-design-opportunity-7447402f0c2f
- http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html
- http://socviz.co/
- Births per month visualization: https://github.com/aaronpenne/Data_Visualization/blob/master/HMD/Births_USA/Births_USA.ipynb
- http://www.datavizcatalogue.com/about.html
- Data acquisition (four parts):
  * https://ikashnitsky.github.io/2017/data-acquisition-one/
  * https://ikashnitsky.github.io/2017/data-acquisition-two/
  * https://ikashnitsky.github.io/2017/data-acquisition-three/
- https://eagereyes.org

## Ideas for specific chapters {-}

Chapter on plot titles: Economist graph of corruption and human development. https://altaf-ali.github.io/ggplot_tutorial/challenge.html#recreating-the-economist-graph
http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html

> Original sources for these data are http://www.transparency.org/content/download/64476/1031428 http://hdrstats.undp.org/en/indicators/display_cf_xls_indicator.cfm?indicator_id=103106&lang=en
> 
> These data consist of Human Development Index and Corruption Perception Index scores for several countries.

Original economist post: https://www.economist.com/blogs/dailychart/2011/12/corruption-and-development


## Datasets to consider {-}

- midwest (ggplot2)
- overlapping points: mpg cty vs hwy
- economics (ggplot2)
- gapminder (gapminder)
- gss_sm (socviz) http://gss.norc.org/Get-Documentation
- organdata (socviz)
- titanic_test, titanic_train (titanic) (is a better source of this dataset available?)
- various datasets of openintro package, https://cran.r-project.org/web/packages/openintro/index.html
- Moby Dick wordcounts, downloaded from http://tuvalu.santafe.edu/~aaronc/powerlaws/data.htm, reference: M. E. J. Newman, "Power laws, Pareto distributions and Zipf's law." Contemporary Physics 46, 323 (2005).
- Berkeley list of health statistics datasets: http://guides.lib.berkeley.edu/publichealth/healthstatistics/rawdata
- Birth and death rates: http://www.mortality.org/cgi-bin/hmd/hmd_download.php
- OECD, http://stats.oecd.org/, e.g. tax as % of GDP

## Required versions of rendering software and R packages {-}

- pandoc: 2.0.6
- rmarkdown: 1.8
- bookdown: 0.5.14
- knitr: 1.18
- cowplot_0.9.2.9900
- ggplot2_2.2.1.9000
- colorspace 1.4
