# Handling overlapping points {#overlapping-points}

Let's revisit this figure from Chapter \@ref(small-axis-labels) and focus on an aspect we ignored there:
```{r}
p <- ggplot(mpg, aes(y=cty, x=displ, color=drv)) +
  geom_point(size=4) + 
  ylab("fuel economy (mpg)") +
  xlab("displacement (l)") +
  scale_color_manual(values=c("#000000", "#E69F00", "#56B4E9"), 
                     name="drive train",
                     breaks=c("f", "r", "4"),
                     labels=c("FWD", "RWD", "4WD")) +
   theme_dviz(19)
stamp_ugly(p)
```
I have labeled this figure "ugly" here because the points overlap and partly obscure each other. A simple way to ameliorate this issue is to use partial transparency:
```{r}
p2 <- ggplot(mpg, aes(y=cty, x=displ, color=drv)) +
  geom_point(size=4, alpha=0.65) + 
  ylab("fuel economy (mpg)") +
  xlab("displacement (l)") +
  scale_color_manual(values=c("#000000", "#E69F00", "#56B4E9"), 
                     name="drive train",
                     breaks=c("f", "r", "4"),
                     labels=c("FWD", "RWD", "4WD")) +
   theme_dviz(19)
stamp_good(p2)
```


